### ISSUE TITLE
Fix test_duplicate_email

### ISSUE THREAD

**Issue by alinashabalina** [olgadanilowa/petsshop#4]
def test_update_user_duplicate_email(create_test_users_body):
    r = UserService().post_user(data=create_test_users_body)

    assert r.status_code == 201

    create_test_users_body_new = deepcopy(create_test_users_body)
    create_test_users_body_new["email"] = _generate_email()
    create_test_users_body_new["name"] = _generate_name()
    create_test_users_body_new["customer_type"] = "private"
    r1 = UserService().post_user(data=create_test_users_body_new)

    assert r1.status_code == 201

    user_id_new = r1.json()['result']['id']
    r2 = UserService().update_user(data=create_test_users_body, user_id=user_id_new)

    assert r2.status_code == 400

 в итоге должно выглядеть вот так, при этом в начале файла надо сделать две локальные функции (не забудь импортировать random и оптимизировать импорты):
 
 def _generate_email():
    email = "test_user" + str(random.randint(1, 10000) + 1) + "@" + random.choice(
        ["mail.ru", "gmail.com", "yandex.ru"])
    return email

def _generate_name():
    name = "test_user" + str(random.randint(1, 10000) + 1)
    return name

пока не разорбралась, почему фикстуры не работают, как я предполагала, возможно, я просто слишком много от них хочу))

**Comment by olgadanilowa** [comment]
+
